@extends('layouts.main')
@section('title')
  @include('pages.page2.sections._title')
@endsection
@section('head')
  @include('pages.page2.sections._head')
@endsection
@section('content')
  @include('pages.page2.sections._body')
@endsection
@section('scripts')
  @include('pages.page2.sections._foot')
@endsection
